name: cfb
description: Package manages state in the application copied from BLOC
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.16.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8

